# Generated by Django 4.2.13 on 2024-05-29 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_created_alter_post_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha de creacion'),
        ),
    ]
